spring:
  application:
    name: eboutique
  datasource:
    username: eboutique
    password: eboutique
    url: jdbc:mysql://localhost:3306/eboutique
  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true